packages:
  - 'packages/*'
  - 'plugins/*'

ignoredBuiltDependencies:
  - core-js-pure

minimumReleaseAge: 7200 # 5 days in minutes

minimumReleaseAgeExclude:
  - minimatch # security fix 9.0.6 released Feb 22 2026
  - brace-expansion # security fix 5.0.6 (CVE-2026-33750)

onlyBuiltDependencies:
  - '@swc/core' # downloads platform-specific prebuilt binaries
  - better-sqlite3 # downloads platform-specific prebuilt binaries
  - cpu-features # faster tests, dep of ssh2 ↓
  - esbuild # downloads platform-specific prebuilt binaries
  - protobufjs # check compat with protobuf version
  - ssh2 # faster tests via native crypto bindings
  - unrs-resolver # downloads platform-specific prebuilt binaries
